### ISSUE TITLE
US2.1: Login Page

### ISSUE THREAD

**Issue by AA789-ai** [leobrod44/Smartess#12]
**Full User Story**: As a user of smartess, i want to be able to sign in to my account with my credentials, and be redirected to my dashboard.

**Story Points:** 5
**Priority:** Must have
**Risk:** High – Without correct login page, nothing will be accessible.
**Child task:** [US7](https://github.com/leobrod44/Smartess/issues/10)

### **Acceptance Criteria:**
- Input bars for email and password are visible when not signed in.
- Characters are typeable in email and password input bars.
- The sign in button is visible.
- Upon entering valid credentials, the user is redirected to its respective dashboard.

### Task Breakdown:
**Frontend:**
- [x] #35
- [x] Create a display message for authentification success or failed. (1 hour)
- [x] Connect to sign in API (0.5 hour)

**Backend:**
- [x] Make function that take email and password as inputs and return the user type and sign in token. (2 hour).
- [x] Make a function that checks for credential validity. (3 hour)

### **Testing Breakdown**
- Ensure that the sign in button works and leads to the dashboard upon entering valid credentials.
- Upon successful login a pop up/notification is displayed which says “success” and redirects users to the dashboard page.
- Unit testing for backend functions.

###  **Demo Steps:**
1. Navigate to smartness website. Make sure you are not logged in.
2. Click on sign in button.
3. Enter valid credentials for email and password.
4. Click on sign in button.
5. Verify if you are redirected to the dashboard and a pop up/notification displaying sucess appears.
