### ISSUE TITLE
US6.4: Individual Ticket Pages & Subsystem

### ISSUE THREAD

**Issue by ChiefsBestPal** [leobrod44/Smartess#14]
## Story Overview
**Full story**: As a user, I want to be able to click on a ticket from the list of tickets, to open a page with specific and detailed information about that ticket

**Story Points: 8**
**Priority: MustHave**
**Risk: Low**

**Child Tasks:**
> Create UI for individual ticket view.
> Integrate ticket details with the backend
> Implement ticket status updates and comment functionality.
> Necessary extra ticket integration with message broker, logger and/or alert manager

## Acceptance Criteria

1. A user can click on a ticket from the tickets list and open a detailed ticket page.
2. The detailed view includes ticket title, id,  description, creation date, status etc.
3. The user can assign users to the ticket (any user type)
4. The user can delete the ticket (admiin or master, not basic)
5. The user can close the ticket (any user type)
6. All changes (status updates, comments) are reflected in real-time.8. Logging system reflects relevant changes or critical statuses as intended internally by the microservices9. CRUD operations are consistently and reliably functional within Rest API / DB interactions due to ticket requests or actions.

### Frontend: 

- [x] Create figma for the ticket page
- [x] #174
- [x] #202
- [x] Unit view link: Add link to view the associated unit for quick navigation.

### Backend
- [x] Fetch data for individual ticket from DB
- [x] Associate user with ticket
- [x] Delete ticket (set ticket status as deleted)
- [x] Close ticket (set ticket status to closed)
- [x] Modify ticket (update ticket data)

### UI Tests
- Ensure ticket details display correctly; consider edge cases for each fields.
- Verify that status updates and comments can be made from the frontend.

### Backend Integration tests
- Test that ticket status changes are saved and reflected across the system.
- Ensure comments are correctly stored and retrieved.
- Make sure Routing between and from different microservices is functional and available as as a whole in backend

### Backend Unit tests
- Test parsing, formatting and verification functions to translate backend raw ticket data to frontend usable ticket data.

### Logging manager and Alert Manager Tests
- Base Integration or System level test within the Message Broker for each of those managers, to make sure they are routed correctly and respond as they do with other backlog features / stories that depend on them ; For their usage in ticket system, an equivalent problem space to another feature/story should be established, and it should provide similar coverage here as when using those managers in that other feature. Data transparency and consistency is key for this current story.
- 
## Demo Steps
I. Log in as any user that has made a request of ticket to their organization/owner.
II. Navigate to the tickets page and click on a ticket 
III. View the ticket details, including the ticket description
IV. Close the ticket
V. Add a comment to the ticket.
VII. Navigate back to the unit view for more information.
