### ISSUE TITLE
US5.1: Dashboard

### ISSUE THREAD

**Issue by laurenrigante** [leobrod44/Smartess#15]
**Full story:** As a user of Smartess, i want to be able to view my dashboard with an agglomeration of information about my projects once i'm logged in.

**Story Points:** 13
**Priority:** Must have
**Risk:** medium
**Child tasks:** 

### Acceptance Criteria:
- The user is logged in and clicks on their profile picture to access their navbar
- The user clicks on the dashboard option and is redirected to their dashboard page
- The page by default contains information about **all projects** 
- The user can use the left side bar to filter which project they would like to view if they would like to view a single project at a time
- The user can click on the sections (units, tickets,users), and they will be redirected to the correct page
- The user can scroll and view summarized information about all the projects  linked to their account
- The user can click the see more button to open a dashboard with that specific project?

### Task Breakdown:
**Frontend:**
- [x] Discuss what contents should be displayed on the page (0.5)
- [x] #23      (6 hr)
- [x] #71
- [x] #72
- [x] #73
- [x] #90
- [x]  Implement the general UI of the page

**Backend:**
- [x] US5.1 TASK 1.B : Adjust DB schema to account for all components in the dashboard. (4hr)
- [x] #145 (7 hr)
- [x] #147 (3 hr)

### Testing Breakdown
- manual testing the UI to make sure all buttons/links redirect to the correct place
- manual testing for responsiveness

### Demo Steps

1. Ensure you are logged in
2. Click on the profile picture navbar
3. Click on dashboard
4. Ensure you are redirected to the dashboard page, which by default will present a summary of ALL PROJECTS
5. verify the information is rendering correctly
6. verify the sections are clickable and redirect to the correct page
7. Use the filters and ensure they are properly filtering content
8. use the search bar to search by address
