### ISSUE TITLE
US4.1: Sidebar 

### ISSUE THREAD

**Issue by eimcharles** [leobrod44/Smartess#31]
**Full story: As a user of Smartess, i want to be able to use the sidebar to navigate through the owner page**

**Story Points:** 5
**Priority:** Must have
**Risk:** low
**Child Tasks:** [US13](https://github.com/leobrod44/Smartess/issues/13)

### Task Breakdown:
**Frontend:**
- [x] Create the dropdown for the building addresses, should be able to switch between buildings in the dropdown [US13](https://github.com/leobrod44/Smartess/issues/13)
- [x] Update the Figma for the side bar based on what sections we will have (confirmed)
- [x] Create the different sections for each category
- Home (dashboard)
- General (units, tickets)
- Security (surveillance, locks, consumption)
- Community (announcements, chat) Information (logs, documentation)

**Backend:**
- Not applicable

### **Testing Breakdown**
- Manual testing the UI to make sure all buttons/links redirect to the correct pages
- Manual testing for responsiveness

###  **Demo Steps:**
1. Log in with appropriate user and credentials 
2. Navigate to the side bar
3. Click on different sections for each category
4. Switch between pages for each created section in sidebar
