### ISSUE TITLE
US6.5: Assign&Unassign Tickets

### ISSUE THREAD

**Issue by TuanAnh-P** [leobrod44/Smartess#49]
**Full Story:** As an organization user, I want to be able to assign tickets to an admin, so that they can manage and resolve tickets efficiently.

**Story points:** 12
**Priority:** Must Have
**Risk:** Low
**Parent Task:** [US6.3](https://github.com/leobrod44/Smartess/issues/33), [US6.4](https://github.com/leobrod44/Smartess/issues/14)
**Child Task:** [US6.6](https://github.com/leobrod44/Smartess/issues/175)

###  **Acceptance Criteria:**
- Upon selecting a ticket from the ticket page, property owners will be redirected to the individual ticket page where they can view its details, along with  a list for employees already assigned to the ticket.
- There is a modal to assign more users to the ticket, where a list of available employees for assignment will appear. Each employee will have an "Assign" button. Clicking this button moves the employee from the available list to the assigned list.
- In the assigned employees list, each employee will have an "Unassign" button. Clicking this button triggers an "are u sure" modal. Once confirmed, the employee moves back to the available list.
- If no employees are assigned, the ticket status remains Open.
- If one or more employees are assigned, the ticket status will change to Pending.
- Property owners can close the ticket at any time by clicking the "Close" button next to the ticket, changing its status to Closed
- User can only assign a maximum of 3 people to a ticket at a time

- MASTER AND ADMIN USER have access to the manage ticket section (assinging, unassigning, closing, deleting tickets)
- basic user only has access to view the ticket information, and to resolve the ticket they r assigned to (us 6.6)

### **Task Breakdown**
**Frontend:**
- [x] [Create Tickets Page UI](https://github.com/leobrod44/Smartess/issues/33)
- [x] #135

- [x] #179
- [x] #210
- [x] #212
- [x] #228
- [x]  US 6.5 T7 Add back button
- [x] Ticket Status Management:
  - Make sure the ticket status updates to Open when no employees are assigned
  - Update the status to Pending/In Progress when one or more employees are assigned
  - Display a Solved flag next next to employees in the assigned employees list when they confirm the ticket is resolved (US 6.6)
  - Implement a Close Ticket button that closes the ticket
- [x] #262
  - Create appropriate success/error messages when assigning/unassigning employees and closing tickets

**Backend:**
- [x] #302
  - Create an API endpoint to fetch available and assigned employees for a ticket
- [x] #364
  - Implement backend logic to assign an employee to ticket and remove an employee from an employee assigned list
  - Make sure the ticket status reflect the correct state (Open to Pending when assigned.)
- [x] #365
  - Handle status updates based on assignment and resolution confirmation
  - Make sure the ticket status reflect the correct state (Open, Pending, Closed)
- [x] #366
  - Notify assigned employees when they are assigned or unassigned from a ticket
  - Trigger notifications when a ticket is closed or when it changes to a new status
- [x] #367
  - Make sure that closing a ticket unassigns all employees and updates the tickets status to Closed.
  - Make sure the ticket status reflect the correct state (Pending to Closed when closed)
 - [x] #428
    - Create and API endpoint to fetch specific ticket along with submitter's info.

### **Testing Breakdown**
- Ensure the API returns the correct lists of available and assigned employees for each ticket.
- Test that the "Assign" button properly moves employees from the available list to the assigned list
- Make sure that the "Unassign" button properly moves employees back to the available list
- Verify that the ticket status updates to Open when no employees are assigned, and to Pending/In Progress when employees are assigned
- Test the Close Ticket button functionality to confirm that it closes the ticket and unassigns all employees
- Test that closing a ticket properly unassigns all employees and updates the ticket's status to Closed

###  **Demo Steps:**
1. Navigate to the Smartness website and log in as a property owner
2. Navigate to the ticket page
3. Select a ticket with the status Open
4. Assign two employees to the ticket by selecting the Assign button next to their name in the available employees list
5. Verify that the two assigned employees move from the available list to the assignment list and that the ticket status changes to Pending/In Progess
7. Unassign one employee from the ticket by selecting the Unassign button next to their name in the assigned employees list
8. Verify that unassigned employee move from the assignment list to the available list and that the ticket status remains to Pending/In Progress (There's still one assigned employee to that ticket)
9. Click the Close Ticket button
10. Confirm that all assigned employees are unassigned automatically and the ticket status changes to Closed
11. Resize the browser window and ensure the page layout remains responsive and usable across various screen sizes.
