### ISSUE TITLE
US3.7: Profile Navbar (logged in)

### ISSUE THREAD

**Issue by Ryan2Li** [leobrod44/Smartess#6]
**Full Story:** As a signed in user, I want to be able to click on my profile picture to open a hovering navbar.

**Story points:** 2
**Priority:** Must Have
**Risk:** Low
**Parent Tasks:** [US1](https://github.com/leobrod44/Smartess/issues/1)

###  **Acceptance Criteria:**
- The user clicking on the profile picture displays a hovering Navbar
- The user can click "Log Out" option in the Navbar to logout and redirect to the sign in page
- Navbar includes “My Dashboard” option
- Navbar includes “My Profile” option
- The user selecting an option or clicking outside the navbar will close it the navbar 
- The user's name is displayed accordingly
- The user's profile picture is displayed accordingly.

### **Task Breakdown**
- [x] Discuss options included in the navbar (5 minutes)
- [x] Discuss the design and layout of the navbar (5 minutes)

**Frontend:**
- [x] create the figma for the open navbar (30 minutes)
- [x]  Implement the clickable toggle profile picture (20 minutes)
- [x]  Implement the UI for the navbar (60  minutes)

**Backend**
- [x] #96 (1 Hour)
- [x] #107 (40 Min)
- [x] #109 (2 Hours)

### **Testing Breakdown**
- Test the navbar when clicking on the profile picture
- Test navbar functionality when clicking the options
- Test logout behaviour
- Unit tests

###  **Demo Steps:**
1. Log in to the application.
2. Click on your profile picture.
3. Click outside the navbar.
4. Click on your profile picture.
5. Click on “Log Out”.
