### ISSUE TITLE
US3.1: Manage Accounts As An Organization

### ISSUE THREAD

**Issue by laurenrigante** [leobrod44/Smartess#64]
**Full story:** As an **organization user**, i want to navigate to the manage accounts section to be able to manage the accounts linked to my organization based on my permissions

**Story Points**: 8
**Priority**: must have
**Risk**: Medium
**Child Tasks**: [US3.2](https://github.com/leobrod44/Smartess/issues/65), [US3.3](https://github.com/leobrod44/Smartess/issues/66), [US3.4](https://github.com/leobrod44/Smartess/issues/67)

### Acceptance criteria:
- Clicking the manage accounts section brings the user to the correct page
- Regardless of permissions, the user should see a section with a list of all of the users linked to the same project as the user.
- The user should see information including the users name, role/permission type, and the address of the project they are involved in 
- The user can filter specific projects to see the users linked to that specific project
- The user can filter for user type (ex: show all admin users, show all basic, show master org user) 
- The user can use the search bar to search for a specific users name , project address, role
- The user should be able to only view the users if they are an organization basic user
- The user should be able to edit ( promote) users if they are organization admin user
- The user should be able to edit (add, delete, promote) users if they are a master organization user

### Task Breakdown:
 **Frontend:**
- [x] #81  (2hr)
- [x] #112
- [x] Render org master user view based on the users role attribute[(US3.2)](https://github.com/leobrod44/Smartess/issues/65)
- [x] Render Organization admin user view [US3.3](https://github.com/leobrod44/Smartess/issues/66)
- [x] Render Organization basic user view [US3.4](https://github.com/leobrod44/Smartess/issues/67)
- [x] #132 

**Backend:**
- [x] #216 
- [x] #230 
- [x] #231
- [x] #233
- [x] #245 
- [x] #247
- [x] #248 
- [x] #249

### Testing Breakdown
1. unit tests for functions
2. manual testing for frontend responsiveness 

### Demo Steps
1.  Click on manage accounts in the side bar, assure you are presented with the manage accounts page
2.  Based on the type of user that is signed in, ensure the right accesses are provided. Add, delete, and promote buttons should be hidden for basic users
3. Switch to an organization account 
4. Add a basic user to the organization
5. Assign this user to a specific project
6. Delete this user from that project
7. Delete this user from the organization
8. Add another basic user
9. Promote user to admin
10. Switch to an admin account
11. Promote a basic user to admin
