### ISSUE TITLE
US3.5:Manage accounts as HUB owner user

### ISSUE THREAD

**Issue by laurenrigante** [leobrod44/Smartess#68]
**Full Story:** As a hub user with owner permissions, I want to navigate to the manage accounts section to be able to view the users involved in my units

**Story Points:** 3
**Priority:** Must have
**Risk:** Medium

### Acceptance criteria:
- Clicking the manage accounts section brings the user to the correct page
- The owner user can view a list of the users involved in his unit hubs
- The user should see information including the users name, role/permission type, address of the project they are involved in 
- The user can filter specific addresses to see the users linked to that specific address
- The user can filter for user type (ex: show all admin users, show all basic) 
- The user can use the search bar to search for a specific user or address or role
- The owner can add users to the hub/address 
- The owner can delete users from a hub/address
- The owner can promote basic users to admin users

### Task Breakdown:
**Frontend**
- [ ] create figma/ same as the figma for organization, double check that it doesnt need tweaks
- [x] #158

**Backend**
- [ ] Fetch all users associated to unit hubs owned by owner
- [ ] Fetch basic data for all users associated to unit hubs owned by owner
- [ ] Create association between user and hub/address (add user)
- [ ] Remove association between user and hub/address (delete user)
- [ ] Change user type from basic to admin

### Testing Breakdown

1. Unit tests for functions
2. Manual testing for frontend responsiveness

### Demo Steps
1. Sign in on a hub owner account
2. Click on manage accounts in the side bar, assure you are presented with the manage accounts page
3.View a list of users involved in the units
4. Add a basic user to the hub
5. Promote the user to an admin user 
6. Delete the user from the hub
7.  Test the filters
8. Test the searchbar
